"""ORM模型注册与建表入口。"""

from backend.database import Base, engine
from backend.models.core import (
    AiDecisionAuditLog,
    Appointment,
    CageUnit,
    Diagnosis,
    Drug,
    DrugInventory,
    FollowupTask,
    Vet,
    AdoptionPet,
    Adopter,
    MatchResult,
    NewsPost,
    ReferralRecord,
    DoctorSupportRequest,
    OperationAuditLog,
    InpatientRecord,
    LabTestOrder,
    Invoice,
    InvoiceItem,
    MedicalRecord,
    NursingLog,
    Owner,
    Pet,
    SchedulingAssignment,
    Prescription,
    PrescriptionItem,
    PurchaseTask,
    Role,
    User,
    Visit,
    KnowledgeNode,
    KnowledgeEdge,
)

__all__ = [
    "Base",
    "Role",
    "User",
    "Owner",
    "Pet",
    "SchedulingAssignment",
    "Visit",
    "KnowledgeNode",
    "KnowledgeEdge",
    "Appointment",
    "MedicalRecord",
    "Diagnosis",
    "CageUnit",
    "InpatientRecord",
    "NursingLog",
    "Drug",
    "DrugInventory",
    "Prescription",
    "PrescriptionItem",
    "Invoice",
    "InvoiceItem",
    "AiDecisionAuditLog",
    "PurchaseTask",
    "FollowupTask",
    "Vet",
    "AdoptionPet",
    "Adopter",
    "MatchResult",
    "NewsPost",
    "ReferralRecord",
    "DoctorSupportRequest",
    "OperationAuditLog",
    "LabTestOrder",
    "init_db",
]


def init_db() -> None:
    """初始化数据库表结构。"""
    Base.metadata.create_all(bind=engine)

